"""request belongs to tutor_service

Revision ID: 128f9ff3b5e9
Revises: 7a75445da0ad
Create Date: 2026-02-06 13:00:18.192464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '128f9ff3b5e9'
down_revision = '7a75445da0ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tutor_service_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_requests_tutor_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_requests_topic_id_topics'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_requests_tutor_service_id_tutor_services'), 'tutor_services', ['tutor_service_id'], ['id'])
        batch_op.drop_column('tutor_id')
        batch_op.drop_column('topic_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topic_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('tutor_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_requests_tutor_service_id_tutor_services'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_requests_topic_id_topics'), 'topics', ['topic_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_requests_tutor_id_users'), 'users', ['tutor_id'], ['id'])
        batch_op.drop_column('tutor_service_id')

    # ### end Alembic commands ###
