"""Add unique constrains on User.name

Revision ID: 7a75445da0ad
Revises: 66e9a9b64636
Create Date: 2026-01-31 17:05:29.206135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a75445da0ad'
down_revision = '66e9a9b64636'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_users_name', ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_name', type_='unique')

    # ### end Alembic commands ###
